version: "3"
services:
  employee-jdbc:
    build:
      context: test.dockerfile
    ports:
      - "8081:8081"
    networks:
      - employee-mysql
    depends_on:
      - mysqldb
 
  mysqldb:
    image: mysql:8
    networks:
      - employee-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bootdb  

networks:
  employee-mysql: 